project_id = "qjcjimesqwtrvligbtla"

[functions.zoom-recording-webhook]
verify_jwt = false

[functions.onboard-portal]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.ayrshare-webhook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
